server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
  instance:
    hostname: discovery         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



logging:
  file: logs/eureka.log
  level:
    com.netflix: ERROR
    org:
      springframework:
        web: ERROR
  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: ERROR

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756